Waypoint

diff --git a/.github/workflows/cross.yml b/.github/workflows/cross.yml
--- a/.github/workflows/cross.yml
+++ b/.github/workflows/cross.yml
@@ -26,23 +26,29 @@ jobs:
             whoami
             env | sort
             ${{ inputs.setup }}
-            sudo ${{inputs.pkg}} perl5
+            sudo ${{inputs.pkg}}
             perl -v
             curl -L https://cpanmin.us | sudo perl - --notest App::cpanminus Module::Build::Tiny
             sudo cpanm --installdeps --notest .
-            sudo cpanm --test-only -v .
-            command1_exit_code=$?
-            # Check if the first command exited successfully (exit code 0)
-            if [ $command1_exit_code -eq 0 ]; then
-              # Run the second command
-              sudo perl -V > test-output-${{ inputs.os }}-${{ inputs.version }}-perl${{ inputs.perl }}.${{inputs.perl_subversion}}-${{ inputs.arch }}.txt
-              command2_exit_code=$?
-            else
-              # Print error message to a file (replace "error.log" with your desired filename)
-              echo "Error!" > test-output-${{ inputs.os }}-${{ inputs.version }}-perl${{ inputs.perl }}.${{inputs.perl_subversion}}-${{ inputs.arch }}.txt
-              # Exit with the first command's exit code
-              exit $command1_exit_code
-            fi
+
+            # Setup non-privileged user for build and test
+            sudo pw useradd -n tester -m -s /usr/local/bin/bash || true
+            sudo chown -R tester .
+            
+            # Run build and tests as tester
+            sudo -u tester env PATH="/usr/local/bin:$PATH" bash -c "
+                ${{ inputs.setup }}
+                perl Build.PL
+                ./Build
+                ./Build test -v
+                command1_exit_code=\$?
+                if [ \$command1_exit_code -eq 0 ]; then
+                  perl -V > test-output-${{ inputs.os }}-${{ inputs.version }}-perl${{ inputs.perl }}.${{inputs.perl_subversion}}-${{ inputs.arch }}.txt
+                else
+                  echo 'Error!' > test-output-${{ inputs.os }}-${{ inputs.version }}-perl${{ inputs.perl }}.${{inputs.perl_subversion}}-${{ inputs.arch }}.txt
+                fi
+                exit \$command1_exit_code
+            "
           shell: bash
           version: '${{ inputs.version }}'
       - continue-on-error: true
